baseurl = "/"
title = "RqR"
languageCode = "es"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "Ferran" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = "es"
copyright = "&copy; 2018 VilBer"

[Author]
  name = "VilBer"
  bio = "VilBer true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "imag/gritos.jpg"

[Params]
  subtitle = "Un blog de R... el lenguaje de la ciencia" # Subtitle of your site
  description = "Solo un blog de R" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  post_navigation = true
  postSections = ["post"]

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
