baseURL = "/"
languageCode = "es"
title = "RqR"
theme = "Amnix"
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
defaultContentLanguage = "es"
[Params]
  description = "Responsive and configurable Hugo theme"
  homeLayout = "2 columns + sidebar"
  listLayout = "2 columns + sidebar"
  singleLayout = "content + sidebar"
  mainSections = ["post"]

[Params.Widgets]
  recent = true
  recentNum = 5
  recentDate = true
  categories = true
  tags = true

[Params.Share]
  facebook = true
  twitter = true
  reddit = true
