baseurl: /
title: Mainroad
languageCode: es
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar.png
  bio: John Doe's true identity is unknown. Maybe he is a successful blogger or writer.
    Nobody knows it.
  name: John Doe
Params:
  authorbox: yes
  description: John Doe's Personal blog about everything
  logo:
    subtitle: Just another site
  mainSections:
    - post
    - docs
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: no
  sidebar:
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
